repos:
  - owner: sharkdp
    name: fd
  - owner: sharkdp
    name: bat
  - owner: lsd-rs
    name: lsd
  - owner: jqlang
    name: jq
  - owner: StackExchange
    name: dnscontrol
  - owner: junegunn
    name: fzf
  - owner: dandavison
    name: delta
  - owner: Genymobile
    name: scrcpy
