name: Build windows binary
on: push

jobs:
  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-pc-windows-gnu, os: windows-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Build ${{ matrix.job.target }} binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.job.use-cross }}
          command: build
          args: --release --target=${{ matrix.job.target }}

      - name: Rename ${{ matrix.job.target }} binary
        run: mv target/${{ matrix.job.target }}/release/wup.exe target/wup-${{ matrix.job.target }}.exe

      - name: Upload ${{ matrix.job.target }} binary
        uses: actions/upload-artifact@v3
        with:
          name: wup-${{ matrix.job.target }}.exe
          path: target/wup-${{ matrix.job.target }}.exe
